/**
 * Markdown Generator
 *
 * Composes a single Markdown document from the report's sections.
 * Deterministic — identical inputs always produce identical output.
 */

import type { ReportContent } from "../types";

export function generateMarkdown(content: ReportContent): string {
  const lines: string[] = [];

  // Header
  lines.push(`# ${content.title}`);
  if (content.subtitle) lines.push(`### ${content.subtitle}`);
  lines.push("");
  lines.push(`**Session:** ${content.sessionDate}  `);
  lines.push(`**Generated:** ${new Date(content.generatedAt).toISOString()}  `);
  lines.push(`**Report ID:** \`${content.id}\`  `);
  lines.push(`**Type:** ${content.type}  `);
  if (content.eventSubtype) lines.push(`**Event:** ${content.eventSubtype.toUpperCase()}`);
  lines.push("");
  lines.push("---");
  lines.push("");

  // Table of contents
  lines.push("## Table of Contents");
  lines.push("");
  content.sections.forEach((s, i) => {
    const anchor = s.id.replace(/_/g, "-");
    lines.push(`${i + 1}. [${s.title}](#${anchor})`);
  });
  lines.push("");
  lines.push("---");
  lines.push("");

  // Sections (each already has markdown)
  content.sections.forEach((s) => {
    lines.push(s.markdown);
    lines.push("");
    lines.push("---");
    lines.push("");
  });

  // DNA snapshot appendix
  lines.push("# Appendix — DNA Snapshot");
  lines.push("");
  lines.push("| DNA Object | Version | Confidence |");
  lines.push("|------------|---------|-----------:|");
  lines.push(`| ${content.dnaSnapshot.technical.id} | ${content.dnaSnapshot.technical.version} | ${(content.dnaSnapshot.technical.confidence * 100).toFixed(1)}% |`);
  lines.push(`| ${content.dnaSnapshot.options.id} | ${content.dnaSnapshot.options.version} | ${(content.dnaSnapshot.options.confidence * 100).toFixed(1)}% |`);
  lines.push(`| ${content.dnaSnapshot.market.id} | ${content.dnaSnapshot.market.version} | ${(content.dnaSnapshot.market.confidence * 100).toFixed(1)}% |`);
  lines.push(`| ${content.dnaSnapshot.narrative.id} | ${content.dnaSnapshot.narrative.version} | ${(content.dnaSnapshot.narrative.confidence * 100).toFixed(1)}% |`);
  lines.push(`| ${content.dnaSnapshot.forecast.id} | ${content.dnaSnapshot.forecast.version} | ${(content.dnaSnapshot.forecast.confidence * 100).toFixed(1)}% |`);
  lines.push(`| ${content.dnaSnapshot.trade.id} | ${content.dnaSnapshot.trade.version} | ${(content.dnaSnapshot.trade.confidence * 100).toFixed(1)}% |`);
  lines.push(`| ${content.dnaSnapshot.operations.id} | ${content.dnaSnapshot.operations.version} | ${(content.dnaSnapshot.operations.confidence * 100).toFixed(1)}% |`);
  lines.push("");

  // Footer
  lines.push("---");
  lines.push("");
  lines.push("*This report was generated by the ATHENA-X Institutional Report Engine (Stage 15).");
  lines.push("The engine is read-only and performs no calculations — every value originates from validated");
  lines.push("canonical databases or one of the seven DNA intelligence objects. See audit metadata for full traceability.*");
  lines.push("");

  return lines.join("\n");
}
