import { NextRequest, NextResponse } from "next/server";
import { spawn } from "child_process";
import { writeFile, mkdtemp, readFile, unlink, rm } from "fs/promises";
import { tmpdir } from "os";
import { join } from "path";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const GENERATOR_SCRIPT = "/home/z/my-project/scripts/certification/generate_certificate.py";

/**
 * POST /api/certification-pdf
 *
 * Accepts a CertificationState JSON body and returns a PDF binary.
 * The PDF is generated by invoking the Python ReportLab script with
 * the state piped to stdin.
 *
 * This is an internal endpoint used only by the engineering console.
 */
export async function POST(req: NextRequest) {
  try {
    const body = await req.text();

    // Validate JSON
    let parsed: unknown;
    try {
      parsed = JSON.parse(body);
    } catch {
      return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
    }

    if (!parsed || typeof parsed !== "object" || !("certificate" in parsed || "version" in parsed)) {
      return NextResponse.json({ error: "Body must be a CertificationState object" }, { status: 400 });
    }

    // The frontend sends the full CertificationState; the Python script expects
    // the certificate summary. If the body has a `certificate` key, unwrap it.
    const certPayload = (parsed as { certificate?: unknown }).certificate ?? parsed;

    // Write input to a temp file (avoid stdin shell-escaping issues)
    const tmpDir = await mkdtemp(join(tmpdir(), "athena-cert-"));
    const inputPath = join(tmpDir, "input.json");
    const outputPath = join(tmpDir, "certificate.pdf");

    await writeFile(inputPath, JSON.stringify(certPayload), "utf-8");

    // Invoke Python generator
    const result = await new Promise<{ ok: boolean; stderr: string; stdout: string }>((resolve) => {
      const proc = spawn("python3", [GENERATOR_SCRIPT, "--input", inputPath, "--output", outputPath], {
        env: { ...process.env },
      });

      let stderr = "";
      let stdout = "";
      proc.stderr.on("data", (chunk) => { stderr += chunk.toString(); });
      proc.stdout.on("data", (chunk) => { stdout += chunk.toString(); });

      proc.on("error", (err) => {
        resolve({ ok: false, stderr: `spawn error: ${err.message}\n${stderr}`, stdout });
      });

      proc.on("close", (code) => {
        resolve({ ok: code === 0, stderr, stdout });
      });
    });

    if (!result.ok) {
      console.error("Certificate PDF generation failed:", result.stderr);
      // Cleanup
      try { await rm(tmpDir, { recursive: true, force: true }); } catch {}
      return NextResponse.json(
        { error: "PDF generation failed", detail: result.stderr.slice(-2000) },
        { status: 500 }
      );
    }

    // Read the generated PDF
    const pdfBuffer = await readFile(outputPath);

    // Cleanup temp dir
    try { await rm(tmpDir, { recursive: true, force: true }); } catch {}

    // Return as PDF
    return new NextResponse(pdfBuffer, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="athena-x-certification.pdf"`,
        "Content-Length": pdfBuffer.length.toString(),
        "Cache-Control": "no-store, no-cache, must-revalidate",
      },
    });
  } catch (err) {
    console.error("Unexpected error in certification-pdf endpoint:", err);
    return NextResponse.json(
      { error: "Internal server error", detail: err instanceof Error ? err.message : String(err) },
      { status: 500 }
    );
  }
}

export async function GET() {
  return NextResponse.json({
    endpoint: "/api/certification-pdf",
    method: "POST",
    description: "Generate a Production Certification PDF from a CertificationState JSON body",
    usage: "POST with Content-Type: application/json, body = CertificationState object",
  });
}
